source 'https://rubygems.org'

eval(IO.read(File.expand_path('../../shared/Gemfile', __FILE__)), binding)

gem 'dotenv'
gem 'hello_world_app', path: './hello_world_app'
gem 'hello_two_times', path: './hello_two_times'
